# Generated by Django 5.1.2 on 2024-10-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=255)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('local', models.CharField(max_length=255)),
            ],
        ),
    ]
