# Generated by Django 5.1.2 on 2024-11-03 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('evento_associado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.evento')),
            ],
        ),
    ]
