# Generated by Django 5.1.2 on 2024-11-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_participante_ingresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='valor_ingresso',
            field=models.DecimalField(decimal_places=2, default='300', max_digits=8),
            preserve_default=False,
        ),
    ]
